name: Aurora Bug Report Form
description: File a bug report.
#labels: []
# GH Issue titles currently limited to 256 characters
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: POC
    attributes:
      label: Point of Contact
      description: Who is the point of contact for this bug?
      placeholder: ex. Tim Williams
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: input
    id: vendor-other-tickets
    attributes:
      label: Vendor/ALCF/other tickets/IDs
      description: Enter comma-separated list of ticket numbers, Jira hyperlinks, GitHub Issue URLs from other repos, etc...
      placeholder: e.g. RITM0404147, [pmodels/mpich#7333](https://github.com/pmodels/mpich/issues/7333)
    validations:
      required: false
  - type: input
    id: reproducer-path
    attributes:
      label: Reproducer Path
      description: Where is the code to reproduce the bug? filepath on Flare, URL, etc...
      placeholder: ex. /home/zippy/reproducers/xgc42
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Status
      description: Status of the bug?
      #multiple: true
      options:
        - Open
        - Open (WA available)
        - Fix in progress
        - Still investigating
        # - Closed (Application source code bug)
        # - Closed (Resolved by upstream fix)
        # - Closed (other)
        - Unknown
      default: 0
    validations:
      required: true
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Details
      description: Concise description of what the bug is, followed by additional details and context if useful.
      placeholder: |
        More detailed description.

        If reproducer is described here:
        1. Go to '...'
        2. Edit '....'
        3. Run '....'
        4. See error in output: '....'

        Screenshots, if applicable
        <details>
        <summary>Before</summary>

        <!-- Add your screenshots here via paste and ![]() image link/include syntax -->
        </details>

        Relevant log output:
        ```shell
        ```

    validations:
      required: true
  - type: checkboxes
    id: priority
    attributes:
      label: Is this a priority/blocking bug?
      description: Only check if you know what this means
      options:
        - label: Priority
          required: false
  - type: textarea
    id: eta
    attributes:
      label: ETA
      description: When is a fix for the bug expected?
      placeholder: ex. 12/31/2029, Q1 2026
    validations:
      required: false
