name: Aurora Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    id: status
    attributres:
      label: Bug Status
      description: Enter status of the bug
  - type: dropdown
    id: priority
    attributes:
      label: priority
      options:
        - high
        - medium
        - low
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: markdown
    id: tickets
    attributes:
      label: Relevant tracking IDs
      description: vendor/ALCF IDs (Jira hyperlink, Support Ticket #, ....)
      render: 
    validations:
      required: false
