name: Aurora Bug Report Form
description: File a bug report.
title: "title"
labels: []
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: POC
    attributes:
      label: Point of Contact
      description: Who is the point of contact for this bug?
      placeholder: ex. Tim Williams
    validations:
      required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: vendor-other-tickets
    attributes:
      label: Vendor/ALCF/other tickets/IDs
      description: Enter ticket numbers, Jira hyperlinks, etc..
      placeholder: e.g. [pmodels/mpich#7333](https://github.com/pmodels/mpich/issues/7333)
    validations:
      required: false
  - type: input
    id: reproducer-path
    attributes:
      label: Reproducer Path
      description: Where is the code to reproduce the bug?
      placeholder: ex. /home/zippy/reproducers/xgc42
    validations:
      required: true
  - type: input
    id: status
    attributes:
      label: Status
      description: Status of the bug?
      placeholder: ex. Open -- WA available
    validations:
      required: true
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Description
      description: A clear and concise one-line description of what the bug is. Use Additional Details part of form to add more.
      placeholder: Short, one-line description.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: How to reproduce?
      description: Steps to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Edit '....'
        3. Run '....'
        4. See error in output: '....'
    validations:
      required: false
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: I expected a pony.
    validations:
      required: false
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Use paperclip button below to paste screenshots
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Details
      description: Add any other details or context about the problem here.
      placeholder: Additional problem details/context. This can be verbose.
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the priority of this bug?
      options:
        - low
        - medium
        - high
      default: 1
    validations:
      required: false
  - type: input
    id: eta
    attributes:
      label: ETA
      description: When is a fix for the bug expected?
      placeholder: ex. 12/31/2029, Q1 2026
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell

